apiVersion: v1
kind: Service
metadata:
  name: ${APP}-lb-svc       # Must be equal to KubernetesConnectionConfiguration.serviceName
  namespace: ${NAMESPACE}   # Must be equal to KubernetesConnectionConfiguration.namespace
  labels:
    app: ${APP}
spec:
  type: LoadBalancer
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: thinclients
      port: 10800
      targetPort: 10800
  # Optional - remove 'sessionAffinity' property if the cluster
  # and applications are deployed within Kubernetes
  #  sessionAffinity: ClientIP
  selector:
    # Must be equal to the label set for pods.
    app: ${APP}
status:
  loadBalancer: {}