apiVersion: v1
kind: Service
metadata:
  name: ${APP}-np-svc
  namespace: ${NAMESPACE}
  labels:
    app: ${APP}
spec:
  type: NodePort
  ports: # Allowed ports range is 30000-32767
    - name: rest
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: thin
      port: 10800
      targetPort: 10800
      nodePort: 30800
    - name: debug
      port: 8787
      targetPort: 8787
      nodePort: 30087
  # Optional - remove 'sessionAffinity' property if the cluster
  # and applications are deployed within Kubernetes
  #  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  selector:
    # Must be equal to the label set for pods.
    app: ${APP}